# docker-compose.yml
version: "3"
services:
  oneindex:
    image: setzero/oneindex
    environment:
    - REFRESH_TOKEN=0 * * * *
    - REFRESH_CACHE=*/10 * * * *
    volumes:
    - ./config:/var/www/html/config
    - ./cache:/var/www/html/cache